### ISSUE TITLE
Missing comment in the Events API for JettonTransferAction

### ISSUE THREAD

**Issue by troman29** [tonkeeper/tonapi#10]
- Увидеть можно тут https://tonapi.io/v1/event/getAccountEvents?account=EQC3qDjaNf_IUpSO3U0Ssa9XUEoKmNmouS1okltdI72R1rl4&beforeLt=30803779000001&limit=1
- В tonkeeper всё отображается как надо.
- В интерфейсе `tonapi-sdk-js` поле `comment` присутствует.

![photo_2022-08-30_21-06-08](https://user-images.githubusercontent.com/104140659/187511165-d9a49966-59e9-40e1-99c8-e87854e6f8d3.jpg)

**Comment by mr-tron** [comment]
Technically comment is `forward_payload:(Either Cell ^Cell)`  - any binary messages with arbitrary structure. It can be (and will be used) for interacting with dapps. So usually it should have 32-bit prefix for marking message type. And prefix 0x00000000 by agreement  tell us what it's text comment. 
https://explorer.toncoin.org/transaction?account=0:b7a838da35ffc852948edd4d12b1af57504a0a98d9a8b92d68925b5d23bd91d6&lt=30803778000007&hash=594db632029d03608a62d7ec19997bbde28c0c436eb6cd23ba2733fff295727f
Your message `Privet :)` has hex represenation `507269766574203A29`. As you see - no prefix. 

Tonkeeper will change behavior in next release. It will add zero prefix when sending and display text comment only for messages with prefix.

**Comment by troman29** [comment]
@mr-tron 
Thanks for the explanation! We can add a prefix when transferring in our product. But we would also like to be able to read different types of comments (if other popular wallets don't have it either).

Maybe you can put a raw forward_payload in a JettonTransferAction?

**Comment by mr-tron** [comment]
I notified all popular wallets.

**Comment by troman29** [comment]
@mr-tron Thanks! :)
