### ISSUE TITLE
Can't login into account, because <iframe> offset from the button

### ISSUE THREAD

**Issue by LetikGit** [tonkeeper/tonapi#12]
### Bug Type

Functional

### Reproduction steps

1. Click at the top "Login" button in header

### Actual result

Nothing happend.

### Expected result

You follow to the login flow

### Suggested Severity

Medium

### Device

- OS: macOS
- Browser chrome
- Version 105

### Additional Context

This is because the iframe is located below the login button. Check video.

https://user-images.githubusercontent.com/48149254/190638346-f724e83b-d2a5-4842-98da-7b5c2b6a07bc.mov

**Comment by mdusafp** [comment]
Fix were deployed on PROD at 20:44:24 26.09.2022
