### ISSUE TITLE
Thumbnail of jetton doesn't load

### ISSUE THREAD

**Issue by liketurbo** [tonkeeper/tonapi#17]
### Bug Type

UI

### Reproduction steps

Go to some jetton page e.g. https://tonapi.io/jetton/0:d4bb28d6539d0337deeb42228832777cd6413b330a631526fd49fd37e08bd14a

### Actual result

Instead thumbnail shows just a circle (border)

### Expected result

Shows actual jetton's thumbnail

### Suggested Severity

Low

### Device

Desktop:
- OS: Windows 11
- Browser firefox
- Version 104.0.2

### Additional Context

![image](https://user-images.githubusercontent.com/29164042/190651819-e4e776e1-cc9c-4bb6-ab51-51938aa8ebaf.png)

**Comment by mr-tron** [comment]
Fixed
