### ISSUE TITLE
[Tonapi.io] - [Log in] button click area is shifted

### ISSUE THREAD

**Issue by vklimenka-epam** [tonkeeper/tonapi#18]
### Bug Type

UI

### Reproduction steps

1. Open [https://tonapi.io/]
2. Click [Log In] button: specifically top part of the button (see screenshot)
![image](https://user-images.githubusercontent.com/79211743/190654031-118f6709-5115-4cad-bc36-d8980a147a6a.png)
3. Click [Log In] button: specifically bottom part of the button and area below the button (see screenshot)
![image](https://user-images.githubusercontent.com/79211743/190654289-904da841-a9e9-44b6-ab9c-9e22527d00ba.png)

### Actual result

2. Nothing happens after click event. Telegram login widget popup window is not present.
3. Click area is shifted, so user able to trigger telegram widget if clicks the area below actual [Log In] button
![LoginShift](https://user-images.githubusercontent.com/79211743/190655103-f77cf614-781d-4978-bcc3-a76f3c19b6e5.gif)
![image](https://user-images.githubusercontent.com/79211743/190662878-522b7b51-f807-42db-ba80-2bf23a34b807.png)

### Expected result

2. Telegram login widget should be opened in popup window.
5. Telegram log in widget should NOT be triggered if clicked outside button area.

### Suggested Severity

Medium

### Device
Desktop:
OS Windows
Browser: Chrome (105.0.5195.127 (Official Build) (64-bit)), Edge (105.0.1343.33 (Official build) (64-bit))

**Comment by mdusafp** [comment]
Fix were deployed on PROD at 20:44:24 26.09.2022
