### ISSUE TITLE
Unclickable login button in firefox

### ISSUE THREAD

**Issue by LetikGit** [tonkeeper/tonapi#28]
### Bug Type

Functional

### Reproduction steps

1. Try to click on "Login" button in firefox, or around button (to click on iframe)

### Actual result

Nothing happend. 

### Expected result

Login flow

### Suggested Severity

Critical

### Device

OS: macOS
Browser: Firefox
Version: 104.0.2

### Additional Context

Unlike this bug https://github.com/tonkeeper/tonapi/issues/12 where we can click offset out "Login" button and got succesfull login, in this bug we can't login in any case. Login in firefox just broken.

**Comment by mdusafp** [comment]
Fix were deployed on PROD at 20:44:24 26.09.2022
