### ISSUE TITLE
Incorrect number format when displaying tokens

### ISSUE THREAD

**Issue by data-will-be-here** [tonkeeper/tonapi#29]
### Bug Type

UI

### Reproduction steps

1. Open https://tonapi.io/account/EQD_5Gn0KWVVr1nXWuNB_ZJlAWjAdI8LNqO_HTNH7ijeW6m6
2. Scroll to jettons 
3. Look at "Starter Pack presale jetton"
![image](https://user-images.githubusercontent.com/85282394/190888216-8e1809fe-1dae-4e97-8769-f795122a0fe3.png)

### Actual result

Explorer says that user owns 3e-9 EFZJ istead of 0.000000003
![image](https://user-images.githubusercontent.com/85282394/190888274-40af4b81-c3a7-4f64-a117-3d051c842109.png)

### Expected result

![image](https://user-images.githubusercontent.com/85282394/190888265-c2720647-2cba-4d01-977b-446339bd04e0.png)

### Suggested Severity

Medium

### Device

- any

**Comment by mdusafp** [comment]
Fixed and deployed at 02.10.2022 18:25 GMT+3
