### ISSUE TITLE
Clearing search history doesn't work in the mobile version of the app

### ISSUE THREAD

**Issue by prafair** [tonkeeper/tonapi#31]
### Bug Type

Functional

### Reproduction steps

1. Add several search queries for the button "Clear history" to appear
2. Click on "Clear history"
3. Try to search something
4. Open search field on the top

It's better to watch the video:

https://user-images.githubusercontent.com/15040493/190922347-a0cda340-4d1b-420c-b3e9-beb4969a4232.mp4

### Actual result

All previous queries are displayed

### Expected result

The history should be cleared, all previous requests deleted

### Suggested Severity

Low

### Device

Smartphone:
- Device: Samsung Galaxy S20 FE
- OS: Android 12
- Browser: Chrome
- Browser version: 105.0.5195.136

### Additional Context

I also checked it in the desktop version, but it works stably there.

Perhaps this is due to the peculiarities of the mobile version, since there is a search bar on top, but there is no such button in the desktop version. 
It is also known that these values are added to the array in cookies, perhaps it is better to do this through the internal store.

**Comment by mdusafp** [comment]
Issue was fixed
