### ISSUE TITLE
Invalid block coordinates for the Log in event

### ISSUE THREAD

**Issue by isopen** [tonkeeper/tonapi#32]
### Bug Type

UI

### Reproduction steps

[vokoscreenNG-2022-09-18_17-07-57.webm](https://user-images.githubusercontent.com/7373292/190896953-9f2eb138-16a0-43bb-961b-0a23dd58a13f.webm)

### Actual result

Test case:
0. Go to https://tonapi.io/
1. Click on Log in
2. Login window does not appear

Test case:
0. Go to https://tonapi.io/
1. Click outside the login button
2. Login window appears

### Expected result

Only by pressing the `Log in` button the authorization window appear.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: Ubuntu 22
- Browser Google Chrome
- Version 105.0.5195.52

**Comment by mdusafp** [comment]
Issue was fixed
