### ISSUE TITLE
The server responds with a 200 code when receiving a domain bid with invalid values via GET /v1/auction/getBids

### ISSUE THREAD

**Issue by ulanzhusupov** [tonkeeper/tonapi#34]
### Bug Type

Functional

### Reproduction steps

The server responds with a 200 code data: null, when receiving a domain bid with invalid values

**Steps:**
1. Send a GET /v1/auction/getBids with values "кошелёк", "12345", "!@#$%^&"

### Actual result

Response code is 200 and data: null
`{
 "data": null
}`

### Expected result

Response code is 400 and data is:
`{
  "error": "error description"
}`

### Suggested Severity

High

### Device

**Curl:**
curl -X 'GET' \
  'https://testnet.tonapi.io/v1/auction/getBids?domain=%21%22%E2%84%96%3B%25%3A%3F%2A' \
  -H 'accept: application/json'

**Request URL:**
https://testnet.tonapi.io/v1/auction/getBids?domain=%21%22%E2%84%96%3B%25%3A%3F%2A

**Comment by mr-tron** [comment]
According to https://github.com/ton-blockchain/TEPs/blob/master/text/0081-dns-standard.md domain is valid utf-8 string. So it's valid domains.
