### ISSUE TITLE
In response body GET /v1/auction/getCurrent, domain value without .ton

### ISSUE THREAD

**Issue by ulanzhusupov** [tonkeeper/tonapi#35]
### Bug Type

Functional

### Reproduction steps

In response body GET /v1/auction/getCurrent, "domain" value without ".ton"

**Steps:**
1. Send a GET /v1/auction/getCurrent

### Actual result

Domain value without ".ton" at the end
`{
  "data": [
    {
      "bids": 1660050553,
      "date": 1660050553,
      "domain": **"wallet"**,
      "owner": "owner",
      "price": 1660050553
    }
  ]
}
`

### Expected result

Domain name has a ".ton" at the end
`{
  "data": [
    {
      "bids": 1660050553,
      "date": 1660050553,
      "domain": **"wallet.ton"**,
      "owner": "owner",
      "price": 1660050553
    }
  ]
}
`

### Suggested Severity

High

### Device

**Curl:**
curl -X 'GET' \
  'https://tonapi.io/v1/auction/getCurrent' \
  -H 'accept: application/json'

**Request URL:**
https://tonapi.io/v1/auction/getCurrent

**Comment by mr-tron** [comment]
Fixed.
