### ISSUE TITLE
500 Server Error when requesting GET /v1/dns/resolve with domain names except casino.ton

### ISSUE THREAD

**Issue by ulanzhusupov** [tonkeeper/tonapi#36]
### Bug Type

Functional

### Reproduction steps

500 Server Error when requesting GET /v1/dns/resolve with domain names except casino.ton

**Steps**
1. Send a GET /v1/dns/resolve with domain name "wallet.ton"

### Actual result

Error code: 500 Internal Server Error
`
{
    "error": "no rows in result set"
}
`

### Expected result

200 OK
`
{
  "next_resolver": "NEXT_RESOLVER",
  "site": [
    "http://wallet.ton"
  ],
  "wallet": {
    "address": "ADDRESS",
    "has_method_pubkey": true,
    "has_method_seqno": true,
    "is_wallet": true,
    "names": [
      "name"
    ]
  }
}
`

### Suggested Severity

Critical

### Device

**Curl:**
curl -X 'GET' \
  'https://tonapi.io/v1/dns/resolve?name=wallet.ton' \
  -H 'accept: application/json'

**Request URL:**
https://tonapi.io/v1/dns/resolve?name=wallet.ton

### Additional Context

**Response headers:**
 cf-cache-status: DYNAMIC 
 cf-ray: 74cfdf5b3aab697b-FRA 
 content-length: 34 
 content-type: application/json; charset=UTF-8 
 date: Mon,19 Sep 2022 05:20:29 GMT 
 nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800} 
 report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=RconyFl7O8fgswncr7p3D72WsdzwS4b%2BNwl26jq0HEwetx0k3%2FHTDT00tarC9bAR452CjDn3tdeLDPqJIDpY1kfADGm6vrZV7GV1gxBiAnMM7VOqylTF6Fozwg%3D%3D"}],"group":"cf-nel","max_age":604800} 
 server: cloudflare

**Comment by mr-tron** [comment]
domain wallet.ton didn't set any dns records. only 1/5 of all domains have not empty records
