### ISSUE TITLE
500 Server Error when requesting GET /v1/event/getAccountEvents with "limit" parameter less or equal zero

### ISSUE THREAD

**Issue by ulanzhusupov** [tonkeeper/tonapi#37]
### Bug Type

Functional

### Reproduction steps

500 Server Error when attempt requesting GET /v1/event/getAccountEvents with limit parameter less or equal zero

**Steps:**
1. Send a GET /v1/event/getAccountEvents with limit parameter less or equal zero and with right parameters for "account" and "beforeLt"

### Actual result

500 Internal Server Error. Response body:
`
{
    "message": "Internal Server Error"
}
`

### Expected result

400 Client Side Error. Response body:
`
{
  "error": "error description"
}
`

### Suggested Severity

High

### Device

**Curl:**
curl -X 'GET' \
  'https://tonapi.io/v1/event/getAccountEvents?account=0%3ABA60BFBD527C0CD2D70C6396630C50A498AF015B987ADAAD1D4A9E287F604536&beforeLt=25758317000002&limit=-1' \
  -H 'accept: application/json'

**Request URL:**
https://tonapi.io/v1/event/getAccountEvents?account=0%3ABA60BFBD527C0CD2D70C6396630C50A498AF015B987ADAAD1D4A9E287F604536&beforeLt=25758317000002&limit=-1

### Additional Context

**Response headers:**

 cf-cache-status: DYNAMIC 
 cf-ray: 74d001db5d6290a2-FRA 
 content-length: 36 
 content-type: application/json; charset=UTF-8 
 date: Mon,19 Sep 2022 05:44:03 GMT 
 nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800} 
 report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=AoOszu60MwaMYjaXqxcMO5DYJtbGHDcbJm4jZQ8kH7P5F6s4Xmi6LgycMlzyIkUj0hqm6Zf5JDA%2FxQvw6z2JNDaNQLpzaDm18Xy5wbwVdG0Ni0xUDu%2Be461Qfw%3D%3D"}],"group":"cf-nel","max_age":604800} 
 server: cloudflare

**Comment by mr-tron** [comment]
Fixed. Will be in next release.
