### ISSUE TITLE
500 Server Error when requesting GET /v1/blockchain/getAccount with empty parameter "account"

### ISSUE THREAD

**Issue by ulanzhusupov** [tonkeeper/tonapi#38]
### Bug Type

Functional

### Reproduction steps

1. Send a GET /v1/blockchain/getAccount with empty parameter "account"

### Actual result

500 Internal Server Error. Response body:
`
{
    "message": "Internal Server Error"
}
`

### Expected result

400 Client Side Error. Response body:
`
{
  "error": "error description"
}
`

### Suggested Severity

Medium

### Device

App: Postman
Request url:
https://tonapi.io/v1/blockchain/getAccount

**Comment by mr-tron** [comment]
Fixed. Will be in the next release.
