### ISSUE TITLE
Wrong time format displayed in tooltip for transaction

### ISSUE THREAD

**Issue by prafair** [tonkeeper/tonapi#43]
### Bug Type

UI

### Reproduction steps

1. Open a transaction (i.e. https://tonapi.io/transaction/50472d8625378a63cfca65ffcd56c7bd0d9e0542e09573fd76858ffe43c75ce3)

### Actual result

Time = 11:40:21

<img width="1792" alt="bug_tonapi_time_actual_result" src="https://user-images.githubusercontent.com/15040493/191363199-027cb808-101e-408b-8ee5-7adfd129930f.png">

### Expected result

Time = 23:40:21

### Suggested Severity

Low

### Device

Desktop:
- **OS**: macOS Big Sur (11.6.1)
- **Browser**: Chrome
- **Browser version**: 105.0.5195.125 (x86_64)

### Additional Context

Since there was no explicit indication of `p.m` / `a.m`, I decided that the time is still displayed in `24-hour` format;)

**Comment by mdusafp** [comment]
Fixed and deployed at 02.10.2022 18:00 GMT+3

**Comment by prafair** [comment]
@mdusafp nice!
