### ISSUE TITLE
Mobile - Log in button is not working

### ISSUE THREAD

**Issue by v4n3k4** [tonkeeper/tonapi#45]
### Bug Type

Functional

### Reproduction steps

1. Go to https://tonapi.io/
2. Click on "Log in" button

### Actual result

"Log in" button is not working

### Expected result

"Log in" button should work

### Suggested Severity

High

### Device

Smartphone:
- Device: iPhone 7, iPhone XS
- OS: iOS 14.2, iOS 14,2
- Browser: Brave, Safari
- Version: 1.42, 14

### Additional Context

![1111](https://user-images.githubusercontent.com/60569564/191370913-8b9a71aa-7ad4-4622-8e64-ba13c3630152.jpeg)
It's possible that this button works only when screen resolution is high (as on laptop), because when user tries to minimise browser screen then "Log in" button changes and also become non-working. Screen from WEB:
<img width="1280" alt="Screenshot 2022-09-20 at 23 59 23" src="https://user-images.githubusercontent.com/60569564/191372400-f7798ab4-e8cb-46e7-8de1-34f6fa1edbab.png">
Before screen size changing (this button works):
<img width="1280" alt="Screenshot 2022-09-21 at 00 00 55" src="https://user-images.githubusercontent.com/60569564/191372500-d278b7f9-30f7-460b-8bbb-a36e84f52e3d.png">

**Comment by TONFOND** [comment]
Smartphone:

Device: iPhone XS
OS: iOS 15.2.1
Browser: Safari

https://user-images.githubusercontent.com/113825222/192118969-b5e61a58-597a-4596-85c7-f316192ffa9e.mov

**Comment by mdusafp** [comment]
Issue was fixed
