### ISSUE TITLE
Improve UX when getting error from API

### ISSUE THREAD

**Issue by LetikGit** [tonkeeper/tonapi#46]
### Bug Type

UX

### Reproduction steps

1. Log in
2. Go to "Apps"
3. Try to create some app
(with invalid image or name)
4. Got error from API

### Actual result

Error don't displayed on frontend

### Expected result

Display error on frontend

### Suggested Severity

Low

### Device

OS: macOS
Browser chrome
Version 105

**Comment by LetikGit** [comment]
Also on trying to create app with empty logo - JS error in console
`TypeError: t.logo is undefined`
But no error displayed. Maybe disable button with empty logo or display some modal/snackbar with error

**Comment by mdusafp** [comment]
Issue fixed, now logo can be empty
