### ISSUE TITLE
When entering too long text in the 'Search by address and transactions' search field, the cross being too little and sometimes missing 

### ISSUE THREAD

**Issue by julialips** [tonkeeper/tonapi#47]
### Bug Type

UI

### Reproduction steps

1. Open https://tonapi.io/
2. Open Explorer tab 
3. Enter a random text in the search field that will fill in several lines 
4. Start search, send request

### Actual result

The cross near the text in the history almost invisible

### Expected result

The cross should not change the size depending of the text size. 
The search field may be limited to some number of symbols

![image](https://user-images.githubusercontent.com/45575431/191601513-50342ee5-b67f-44d8-ad67-e78f60ab1102.png)

### Suggested Severity

Low

### Device

Desktop:
- Browser: FireFox
- Version: 104.0.2 (64-bit)
- OS: Windows

**Comment by mdusafp** [comment]
Fixed and deployed at 17:40 GMT+3
