### ISSUE TITLE
TON API_Не сворачивается меню истории + сообщение об ошибке не представлено всплывающим окном

### ISSUE THREAD

**Issue by TONFOND** [tonkeeper/tonapi#49]
### Bug Type

UX

### Reproduction steps

1. вводим несколько поисковых адресов
2. при очередном адресе происходит загрузка состояния, но меню истории не сворачивается
3. при формировании ошибочного запроса ошибка выдается в том же окне, вместо подсказки или всплывающего окна

### Actual result

меню истории не сворачивается
при формировании ошибочного запроса ошибка выдается в том же окне, вместо подсказки или всплывающего окна

### Expected result

меню истории должно сворачиваться
при формировании ошибочного запроса ошибка должна выдаваться на той же странице

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
OS: iOS 12.6
Browser Google
Version 105.0.5195.102

### Additional Context

https://user-images.githubusercontent.com/113825222/192119934-0674a368-3aa8-4d3f-a735-d8e06346823c.mov

**Comment by mdusafp** [comment]
Fixed and deployed at 17:15 GMT+3
