### ISSUE TITLE
The "Try again" button doesn't work

### ISSUE THREAD

**Issue by isopen** [tonkeeper/tonapi#50]
### Bug Type

UX

### Reproduction steps

[vokoscreenNG-2022-09-26_00-14-34.webm](https://user-images.githubusercontent.com/7373292/192156425-97631147-4ebe-49b4-b166-9931834455d5.webm)

### Actual result

The "Try again" button does not work

### Expected result

Fix the "Try again" button. If possible, change the validators to more adequate ones.
So that there is no transition to a separate page if there is a validation error.

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: Ubuntu 22
- Browser Google Chrome
- Version 105.0.5195.52

**Comment by mdusafp** [comment]
Fixed at 01.10.2022 19:00 GMT+3

**Comment by isopen** [comment]
Thanks. It worked.
