### ISSUE TITLE
Pagination error for endpoint v1/nft/searchItems

### ISSUE THREAD

**Issue by ad4ptec** [tonkeeper/tonapi#55]
### Bug Type

Functional

### Reproduction steps

1. Open Postman
2. Receive Bearer Token
3. Create get request with the following link: https://tonapi.io/v1/nft/searchItems?limit=10&offset=10

### Actual result

Response 400 bad request
![image](https://user-images.githubusercontent.com/15279423/195687172-e33a07fd-d0c4-41a8-b461-8076b0b22040.png)

### Expected result

If you specify offset 0, then the server will return the correct data
![image](https://user-images.githubusercontent.com/15279423/195688157-e5c4a806-0149-4a60-9d60-be775354c069.png)

### Suggested Severity

Medium

### Device

Desktop:
- OS: Win11
- Postman v10

**Comment by truefantomas** [comment]
А что вы пытаетесь найти? У вас не указан ни адрес коллекции ни адрес овнера? Можете уточнить чтобы произвести запрос?
