### ISSUE TITLE
The NFT metadata is not loaded

### ISSUE THREAD

**Issue by data-will-be-here** [tonkeeper/tonapi#56]
### Bug Type

Functional

### Reproduction steps

https://tonapi.io/v1/nft/searchItems?collection=EQBZt79z3nRH9Seo3Xtr50QUCCSXRhpuRsWsABqVagRMWoKb&limit=5000&offset=0&include_on_sale=true&owner=EQD_5Gn0KWVVr1nXWuNB_ZJlAWjAdI8LNqO_HTNH7ijeW6m6

query, among other things, returns token ID 138 and token ID 137 - with an empty metadata body.

### Actual result

```
{
         "address":"0:d1969e1b4c946c258581ca8c694d6f382e6ccb523e42725be1b1c43987eb72a2",
         "approved_by":null,
         "collection":{
            "address":"0:59b7bf73de7447f527a8dd7b6be74414082497461a6e46c5ac001a956a044c5a",
            "name":"NeuroTonPunks"
         },
         "collection_address":"0:59b7bf73de7447f527a8dd7b6be74414082497461a6e46c5ac001a956a044c5a",
         "index":137,
         "metadata":{
            
         },
         "owner":{
            "address":"0:ffe469f4296555af59d75ae341fd92650168c0748f0b36a3bf1d3347ee28de5b",
            "is_scam":false
         },
         "verified":true
      },
```

### Expected result

the metadata should be there.
see https://getgems.io/collection/EQBZt79z3nRH9Seo3Xtr50QUCCSXRhpuRsWsABqVagRMWoKb/EQB5baNfiniZFgVyQnRTYH4TDOS2mY4mKdKUt0SLM0El9boB

### Suggested Severity

Critical

### Device

- any

**Comment by truefantomas** [comment]
Это что-то у вас на бэке. Все работает перейдя по запросу. И через с рок адресами тоже работает без проблем.

**Comment by mr-tron** [comment]
бывают задержки в индексации
