### ISSUE TITLE
Back auction link always go to TON DNS auctions

### ISSUE THREAD

**Issue by XaBbl4** [tonkeeper/tonapi#57]
Telegram usernames auction link go to TON DNS auctions

![2022-10-27_11-14-41](https://user-images.githubusercontent.com/697282/198230068-dec64666-b995-418d-89d6-216d4c234263.png)

**Comment by mr-tron** [comment]
Can't reproduce. `.ton` and `.t.me` both are selling via similar mechanics and we display their in one interface. Only with filter by TLD. Telergam usernames are just domains in TON DNS.
