### ISSUE TITLE
500 error afer entering Cyrillic in the search field

### ISSUE THREAD

**Issue by machnev** [tonkeeper/tonapi#58]
### Bug Type

Other

### Reproduction steps

1. Open https://tonapi.io/account
2. Type 'кирилица' in the search field
3. Press 'Enter'

### Actual result

'500 error' page opens

### Expected result

 the 'no-results' page opens

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: Windows 11 Pro
- Browser Chrome
- Version 107.0.5304.107

**Comment by mr-tron** [comment]
fixed
