### ISSUE TITLE
The relation between the NFT and the owner is lost during the auction

### ISSUE THREAD

**Issue by troman29** [tonkeeper/tonapi#6]
## Problem
Мы отображаем NFT пользователя, и когда он ставит их на аукцион - они пропадают.
Для пользователя это совсем не очевидно и выглядит как баг.

- Используем запрос `/v1/nft/searchItems?owner=<address>&include_on_sale=true`.
- Речь идёт об аукционах на смарт-контрактах [GetGems](https://getgems.io), которые появились недавно.

**Comment by mr-tron** [comment]
fixed
