### ISSUE TITLE
/v1/blockchain/getBlock example returns 400 Invalid format for parameter block_id

### ISSUE THREAD

**Issue by romanovichim** [tonkeeper/tonapi#60]
### Bug Type

Functional

### Reproduction steps

1. request /v1/blockchain/getBlock with param from example  'block_id' : (-1,4234234,-23423523535345353454)
![tonapierror](https://user-images.githubusercontent.com/18370291/205034922-fef24420-3059-40eb-bebb-ecfc077f8af8.PNG)

### Actual result

response: 'message': "Invalid format for parameter block_id: multiple values for single value parameter 'block_id'"

### Expected result

Expected 200 with info about block

### Suggested Severity

Medium

### Device

Desktop :
- OS: Windows
- Browser chrome
- Version  107.0.5304.123

### Additional Context

By the way I think passing three parameters in one string is not the best practice...

**Comment by mr-tron** [comment]
fixed
