### ISSUE TITLE
Incorrect token balance of jUSDT

### ISSUE THREAD

**Issue by bunnychai** [tonkeeper/tonapi#77]
### Bug Type

UI

### Reproduction steps

1. Bridge jUSDT to your ton address
2. https://tonviewer.com/your_addr -> view all tokens
3. Balance of jUSDT is incorrect
4. Click on the Jetton wallet address
5. It shows a different balance

### Actual result

Incorrect balance is shown.
The balance is 1000 times smaller.

### Expected result

Same balance in 'view all tokens' page and the detailed page.

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: macOS v12.3
- Browser chrome
- Version 112.0.5615.137

**Comment by mr-tron** [comment]
fixed
