### ISSUE TITLE
Changed Icon Image, but still show Old Image in cache

### ISSUE THREAD

**Issue by ownershipcoin** [tonkeeper/tonapi#81]
### Bug Type

UX

### Reproduction steps

Dear Sir, 

Thank you for you attention to this issue. I have changed the icon image for the Jetton token, as you can see from this smart contract address:https://tonscan.org/jetton/EQD41BrP5AX8egzrSN17OHN9SCatDzYti7Z5TwbrNLwO1kRx
The new icon image is here:
(https://i.tonscan.org/resize/ZRlJVpUXeNQDLTT72wF7_AcCYGW8K0InxNASosl7jAc/f:jpg/rs:fit:72:72:0/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL293bmVyc2hpcGNvaW4vamV0dG9uL21haW4vT0MuanBn.jpg)

**Issue:**
However, if you navigate to the wallet holder:https://tonscan.org/address/EQA5glq9UBU-xM368m_7W-TrPCz8u3sdrOki3RsHxh38ZINN#tokens, you will see the old image. The old image url is https://cache.tonapi.io/imgproxy/rdXRETFvGvI2TF2dw2JvTYT21Rf4OZpv5hfxvQXItgE/rs:fill:200:200:1/g:no/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL293bmVyc2hpcGNvaW4vamV0dG9uL21haW4vT0MuanBn.webp

**Issue 2:**
The Tonkeeper wallet also showing the Old Image.

### Actual result

If you navigate to the wallet holder:https://tonscan.org/address/EQA5glq9UBU-xM368m_7W-TrPCz8u3sdrOki3RsHxh38ZINN#tokens, you will see the old image. 

The old image url is https://cache.tonapi.io/imgproxy/rdXRETFvGvI2TF2dw2JvTYT21Rf4OZpv5hfxvQXItgE/rs:fill:200:200:1/g:no/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL293bmVyc2hpcGNvaW4vamV0dG9uL21haW4vT0MuanBn.webp

### Expected result

The new icon image should be:
(https://i.tonscan.org/resize/ZRlJVpUXeNQDLTT72wF7_AcCYGW8K0InxNASosl7jAc/f:jpg/rs:fit:72:72:0/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL293bmVyc2hpcGNvaW4vamV0dG9uL21haW4vT0MuanBn.jpg)

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

**Comment by mr-tron** [comment]
fixed.
