### ISSUE TITLE
Inconsistent TonAPI data

### ISSUE THREAD

**Issue by emiliana32** [tonkeeper/tonapi#82]
Good morning,
one of the key feature of a blockchain is that it is transparent and can be analysed by anyone. However, in the case of the TON blockchain, which is in the top 15 according to CMC, and from a technological point of view is the most promising one, it seems impossible to know what the statistics are.
[CMC](https://coinmarketcap.com/currencies/toncoin/)
-Circulating Supply: 3,431,892,088
-Total Supply: 5,047,558,528
[Tonscan](https://tonscan.org/stats)
-Circulating Supply: 3,414,166,606
-Total Supply: 5,047,558,528
[Tontech](https://tontech.io/stats/)
-Circulating Supply: 3,436,986,739
-Total Supply: 5,089,155,274
[TonStat](https://www.tonstat.com/)->data from TonAPI
-Circulating Supply: ?
-Total Supply: 5,089,086,273[
CG](https://www.coingecko.com/en/coins/toncoin)
-Circulating Supply: 1,473,591,410
-Total Supply: 5,057,362,773
Is anyone able to explain the reason for these inconsistencies, despite the source being the same and transparent?
Thank you

**Comment by mr-tron** [comment]
TON has unlimited emission. so every block system produces few TONs - https://tonviewer.com/transaction/e94c68efe95c00ffd04e3db3617de67650604e845ef416314663717a017d5e69
Different resources uses different snapshots and probaly skips some accounts by different reasons.
5,089,309,338.398196663 - for example this sum of all acounts balances at this moment.  but it grew up while i have been written this message.

**Comment by emiliana32** [comment]
Thank you for your reply. However, this is the first time I have seen a blockchain project where the various explorer/statistics websites have such different and inconsistent values. This contradicts the transparency principle of the blockchain.
Furthermore, TON has an inflation of 0.6%, but thanks to the 50% burning of transaction fees, there is a breakeven point between creation due to inflation and destruction due to burning. So tokenomics can be deflationary once it reaches about 500 tps (if you're interested I can bring back the calculations).

**Comment by emiliana32** [comment]
Hello,
I have found another data inconsistency. Please let me know if it is better to open a new issue.
[Tonscan](https://tonscan.org/stats) stake 518 M
[TonTech](https://tontech.io/stats/) stake 275.43
[TonStat](https://www.tonstat.com/) stake 489 M
Which one is correct? I suppose the value is calculated in different ways.
Thank you

**Comment by mr-tron** [comment]
staking has two half-periods and full stake splited on two parts. also elector account has money which doesn't participate in staking. So calculating total amount can be difficult.
i think tonstat gave the most precious value.

**Comment by emiliana32** [comment]
Thank you for the quick reply. I have no doubt how difficult it can be, however the various data aggregators should agree on the values. For example, tonscan calculates the total stakes of the validators of the current round and the frozen stakes of the validators of the previous round [link](https://github.com/catchain/tonscan/issues/67). Why do you think your way is better?
Thank you
