### ISSUE TITLE
Linux destop Tonkeeper software connection QR-code scanning error : "unknown protocol version : undefined"

### ISSUE THREAD

**Issue by pega7sus** [tonkeeper/tonapi#85]
### Bug Type

Functional

### Reproduction steps

1. go to fragment.com web site
2. pop up a TON connect QR-code
3. launch Tonkeeper (on Linux Mint 21.1)
4. Click the scan button in Tonkeeper
5. Point to the QR-code with webcam (video image looks OK)
6. When the QR-code image is stable Tonkeeper quickly displays error : "unknown protocol version : undefined"

Being able to have a no-SIM login on Telegram is not enough, as long as the process is smartphone dependent; each smartphone has a unique identifier - that's why I'm trying to complete the process on x86.

### Actual result

Tonkeeper error : "unknown protocol version : undefined"

### Expected result

Tonkeeper sync ID with fragment.com

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: Linux Mint 21.1
- Browser Firefox 121.0.1

Smartphone (please complete the following information):
Desktop only process

**Comment by mr-tron** [comment]
tonkeeper for web doesn't implement ton connect 1.0 and fragment does't implement ton connect 2.0. so for fragment only mobile version
